name: 'PR develop 2 main'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  develop2main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: check diff
        id: diff
        run: echo "::set-output name=changed::$(git diff main develop | wc -l)"
      - name: output if
        if: ${{ steps.diff.outputs.changed != '0' }}
        run: echo "差分あり：${{steps.diff.outputs.changed}}"
      - name: create pull request for develop 2 main
        id: create-pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PULL_REQUEST_URI=$(gh pr create --base main --head develop --title "PRDリリース" --body "必要であれば何か書く" -l "release" --reviewer daiki510)
