name: 'PR develop 2 main'

on:
  workflow_dispatch:

jobs:
  develop2main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Get diff between main and develop
        id: get-diff
        uses: technote-space/get-diff-action@v6
        with:
          BASE: 'main'
          HEAD: 'develop'
      - name: create pull request for develop 2 main
        if: ${{ steps.get-diff.outputs.files != '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PULL_REQUEST_URI=$(gh pr create --base main --head develop --title "PRDリリース" --body "必要であれば何か書く" -l "release" --reviewer daiki510)
