name: 'PR develop 2 main v2'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 1 * * 1'

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'PRDリリース'
          body: 'This pull request is automatically created to review the changes made in the feature branch.'
          branch: develop # 対象ブランチ1
          base: main # 対象ブランチ2
          labels: 'release'
